"""Add director to production table

Revision ID: 32d08fb7694f
Revises: fd12130f786e
Create Date: 2023-04-07 10:05:38.171322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d08fb7694f'
down_revision = 'fd12130f786e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_column('director')

    # ### end Alembic commands ###
